language: node_js
node_js: '10'
cache: yarn
install: yarn

stages:
  - Test
  - Docs

jobs:
  include:
    - stage: Test
      name: 'Running Tests'
      script: yarn run test:coverage
      after_success: cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

    - stage: Docs
      name: 'Building Docs'
      if: branch = master
      script: yarn run build
      before_deploy:
        - cd docs
        - yarn install
        - yarn run build
        - cd ..
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: ./docs/build
        target_branch: gh-pages
        on:
          branch: master
