language: node_js
node_js:
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
cache: yarn

script:
    - yarn run travis

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

before_deploy:
  - cd docs
  - yarn install
  - yarn run build
  - cd ..
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: ./docs/build
  on:
    branch: master
